const double birdStartX = 100;
const double birdStartY = 100;
const double birdWidth = 60;
const double birdHeight = 40;
const double gravity = 800;
const double jumpStrength = -300;
const double groundHeight = 200;
const double groundSpeed = 200;
const double pipeInterval = 2;
const double pipeGap = 200; // gap between top and bottom pipes
const double minPipeHeight = 50; // minimum height for pipes
const double pipeWidth = 60;
